CREATE TABLE IF NOT EXISTS TRANSACTIONS (
    TRANSACTION_ID INT NOT NULL AUTO_INCREMENT,
    ORDER_ID INT,
    PRODUCT_ID INT,
    QUANTITY INT,
    PRICE DECIMAL(10,2),
    PRIMARY KEY (TRANSACTION_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDER_DETAILS(ORDER_ID)
);