CREATE TABLE IF NOT EXISTS PAYMENTS (
	PAYMENT_ID INT NOT NULL AUTO_INCREMENT,
	ORDER_ID INT,
	PAYMENT_DATE DATE,
	AMOUNT DECIMAL(10,2),
	PRIMARY KEY (PAYMENT_ID),
	FOREIGN KEY (ORDER_ID) REFERENCES ORDER_DETAILS(ORDER_ID)
);