CREATE TABLE IF NOT EXISTS CUSTOMER_DETAILS (
	CUSTOMER_ID INT NOT NULL AUTO_INCREMENT,
	FIRST_NAME VARCHAR(255),
	LAST_NAME VARCHAR(255),
	EMAIL VARCHAR(255),
	PHONE VARCHAR(20),
	ADDRESS VARCHAR(255),
	PRIMARY KEY (CUSTOMER_ID)
);