CREATE TABLE IF NOT EXISTS ORDER_DETAILS (
	ORDER_ID INT NOT NULL AUTO_INCREMENT,
	CUSTOMER_ID INT,
	ORDER_DATE DATE,
	TOTAL_AMOUNT DECIMAL(10,2),
	PRIMARY KEY (ORDER_ID),
	FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER_DETAILS(CUSTOMER_ID)
);